# SPDX-FileCopyrightText: Â© 2025 Eashwar Ranganathan <eashwar@eashwar.com>
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse-lint-file
        exclude: ^(Cargo\.lock|uv\.lock)$
